---
title: "Term Project"
author: "Leslie Speight Youtsey and Elizabeth Weatherup"
date: "10/22/2020"
output: html_document
---

```{r}
bats_flux <- read.csv("bats_flux.csv")

delete.na <- function(DF, n=0) {
  DF[rowSums(is.na(DF)) <= n,]
} #Function that takes rows out that contains NAs 

bats_flux.noNA <- delete.na(bats_flux) # Take out rows containing NAs 


Data <- subset(bats_flux,select = c("cr","dep","yymmdd1","yymmdd2","Lat2","Lat2.1","Long1","Long2","M_avg","C_avg","N_avg","P_avg"))

Data.noNA <- delete.na(Data)

#Data_noNA <- write.csv(x= Data.noNA,file = "Data_noNA.csv")
```


ANOVA Trial 
```{r}
#we want to make predictions on the Mass average flux. 

# we want to compare this against depth and C,N,P fluxes 

# Depth is categorical 
# N,P,C are numerical 

library(psych) # for `pairs.panels()`
library(lattice)

ANOCOVA.data <- subset(Data.noNA, select = c("dep", "M_avg", "C_avg","N_avg","P_avg"))
as.character(ANOCOVA.data$dep) # need to make dep categorical not numerical 
attach(ANOCOVA.data)

summary(ANOCOVA.data)

pairs.panels(data.frame(dep,C_avg,N_avg, P_avg, M_avg))

xyplot(M_avg ~ C_avg | dep, 
                  main="Fig2a: Activity level-specific scatterplots"
           )

    xyplot(M_avg ~ C_avg, groups=dep, 
                  auto.key=TRUE,
                  main="Fig2b: Scatterplot with color=group level"
           )
    
    xyplot(M_avg ~ C_avg, groups=dep, 
                  type=c("p","r"), # `p` for _points_, `r` for _regression line_
                                   # see https://stackoverflow.com/questions/12972039/plotting-xyplot-with-regression-line-on-lattice-graphics for more
                  auto.key=TRUE,
                  main="Fig3: Three standalone depth level-specific `lm()` fits"
           )
```

Bar graph trial
```{r}
# this code is to specify the depth I want to look at that contains the rows and the columns
Study_depths <- c("150", "200", "300", "400" ) #vector of depths I want to retain

Study_Rows <- which(bats_flux$dep %in% Study_depths) #which() to ask R which rows in spp name are on the list


bats_flux2 <- bats_flux[Study_Rows,] #has all the rows we want as well as all the columns

```


Mean and se of each depth of C-flux


```{r}
Cflux <- bats_flux2[-which(is.na(bats_flux2$C_avg)),] #removes na from C-avg
Cflux.noNAs <- delete.na(bats_flux2)

levels(as.factor(Cflux.noNAs$dep150)) #this looks at the distribution of toxins in the organism selected


dep150 <- subset(Cflux.noNAs, dep=="150") #focusing on mean of C-avg at depth 150
dep150

muCflux150 <- mean(dep150$C_avg, data=dep150)
muCflux150

s.e150 <- muCflux150 * sqrt(10)


dep200 <- subset(Cflux.noNAs, dep=="200") #focusing on mean of C-avg at depth 200
dep200

muCflux200 <- mean(dep200$C_avg, data=dep200)
muCflux200

dep300 <- subset(Cflux.noNAs, dep=="300") #focusing on mean of C-avg at depth 300
dep300

muCflux300 <- mean(dep300$C_avg, data=dep300)
muCflux300

dep400 <- subset(Cflux.noNAs, dep=="400") #focusing on mean of C-avg at depth 400
dep400

muCflux400 <- mean(dep400$C_avg, data=dep400)
muCflux400

```

```{r}
site.freq <- table(bats_flux2$dep) #Creates table with frequency of each Site
site.freq

barplot(site.freq)


barplot(site.freq[order(site.freq, decreasing = T)],
        horiz = F,         #Horizontal
        border = NA,    
        
        main = "Average C Flux at Depths: 150, 200, 300, 400",
        xlab = "Depths", ylab = "Average C Flux")


```









Looking at fluxes over depths and hypothesizing that flux will decrease over depth 
```{r}
# separate each flux into its own dataframe 
# delete rows that contain NAs 
C_flux.data <- delete.na(subset(Data,select = c("cr","dep","yymmdd1","yymmdd2","Lat2","Lat2.1","Long1","Long2","C_avg")))
N_flux.data <- delete.na(subset(Data,select = c("cr","dep","yymmdd1","yymmdd2","Lat2","Lat2.1","Long1","Long2","N_avg")))
P_flux.data <- delete.na(subset(Data,select = c("cr","dep","yymmdd1","yymmdd2","Lat2","Lat2.1","Long1","Long2","P_avg")))
M_flux.data <- delete.na(subset(Data,select = c("cr","dep","yymmdd1","yymmdd2","Lat2","Lat2.1","Long1","Long2","M_avg")))

````


# Title : Analyze water quality data 

# Abstract: So this project will involve bla bla bla 

# Introduction: 

# Toolbox discussion:

# Description:

# Implementation:

# Results discussion:

# Limitations:

# References:

